server:
   port: 8888
spring:
   profiles:
       active: native
   cloud:
       config:
           server:
               native:
                   searchLocations: file:////Users/waldemarmodzelewski/git/SMS_v1/STS_ConfigurationServer/src/main/resources/config/b,
                                    classpath:config/
                                    